<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit6aab73ad31e53960ecb5f396c6641b02
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'Psr\\Log\\' => 8,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Psr\\Log\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/log/Psr/Log',
        ),
    );

    public static $prefixesPsr0 = array (
        'C' => 
        array (
            'Cielo' => 
            array (
                0 => __DIR__ . '/../..' . '/src',
            ),
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit6aab73ad31e53960ecb5f396c6641b02::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit6aab73ad31e53960ecb5f396c6641b02::$prefixDirsPsr4;
            $loader->prefixesPsr0 = ComposerStaticInit6aab73ad31e53960ecb5f396c6641b02::$prefixesPsr0;
            $loader->classMap = ComposerStaticInit6aab73ad31e53960ecb5f396c6641b02::$classMap;

        }, null, ClassLoader::class);
    }
}
